version: "3.0"

services:
  mztalk-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: gateway
      MYSQL_ROOT_PASSWORD: dlquf!2tkfkd!2
      MYSQL_USER: gateway
      MYSQL_PASSWORD: 1234
#       MYSQL_ROOT_HOST: '43.200.113.144'
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    networks:
      - mztalk-mysql-net
  test-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mztalk-mysql:3306/gateway?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: gateway
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - 8000:8000
    depends_on:
      - mztalk-mysql
    networks:
      - mztalk-mysql-net

networks:
  mztalk-mysql-net:
         driver: bridge
