version: "3.7"

services:
  db-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: gateway
      MYSQL_USER: gateway
      MYSQL_PASSWORD: 1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3307:3306
    networks:
      - mztalk-mysql-net
  test-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db-mysql
    networks:
      - mztalk-mysql-net

networks:
  springboot-mysql-net:
         driver: bridge
