server:
  port: 8000

eureka:
  client:
    register-with-eureka:  true
    fetch-registry: true
    service-url:
      defaultZone: http://3.39.183.175:8761/eureka
  instance:
    hostname: gateway-api
    prefer-ip-address: true


spring:
  main:
    web-application-type: reactive
  application:
    name: gatewayservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mztalk-mysql:3306/gateway?autoReconnect=true&useSSL=false
    username: gateway
    password: 1234
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
=======
      ddl-auto: create
>>>>>>> f58b63fe2e8118664db5ff5b74daac6d28b0e35e
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1/5501"
            allow-credentials: true
            allowedHeaders:
              - UserRole
              - x-requested-with
              - Authorization
              - Content-Type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
              - RefreshToken
              - UserNo
              - UserNickname
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - PATCH
            exposedHeaders:
              - Authorization
              - RefreshToken
              - LoginResult
              - UserNo
              - UserNickname
              - UserRole
              - Content-Type
      routes:
        - id: mentor-service
          uri: lb://mentor-service
          predicates:
            - Path=/mentors/**
          filters:
            - UserJwtAuthorizationFilter
            - MentorFilter
        - id: bung-service
          uri: lb://bung-service
          predicates:
            - Path=/bung/**
          filters:
            - UserJwtAuthorizationFilter
            - BungFilter
        - id: auction-service
          uri: lb://auction-service
          predicates:
            - Path=/auction/**
          filters:
            - UserJwtAuthorizationFilter
            - AuctionFilter
        - id: story-service
          uri: lb://story-service
          predicates:
            - Path=/story/**
          filters:
            - UserJwtAuthorizationFilter
            - StoryFilter
        - id: login-service
<<<<<<< HEAD
          uri: lb://login-service
=======
          uri: http://52.78.207.50:8085/login
>>>>>>> f58b63fe2e8118664db5ff5b74daac6d28b0e35e
          predicates:
            - Path=/login/**
        - id: resource-server
          uri: http://52.79.34.80:8086/resource
          predicates:
            - Path=/resource/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Allow-Headers
